sudo: required

dist: trusty

git:
  depth: 1

language: node_js

node_js:
- '6'
- '7'
- stable
services: mongodb
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

matrix:
  fast_finish: true
